[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'shanghai'

optimizer = true
#optimizer_runs = 1_000_000 # cmETH runs
optimizer_runs = 200 # COOK runs
solc_version = "0.8.20"

fs_permissions = [{ access = "read-write", path = "./deployments"}, { access = "read", path = "./"}]

remappings = [
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-oapp-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/oapp',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
]

[fmt]
line_length = 120
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
